"""empty message

Revision ID: f4b2ddc23acc
Revises: 
Create Date: 2019-10-02 11:35:20.782307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b2ddc23acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogposts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('create_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('modified_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('blogposts',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('contents', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('create_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('modified_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blogspot_pkey'),
    sa.UniqueConstraint('contents', name='blogspot_contents_key')
    )
    # ### end Alembic commands ###
